### ISSUE TITLE
Acknowledgements and Copyright section not showing in Epub 

### ISSUE THREAD

**Issue by jackkinsella** [adamniedzielski/admission#10]
There is some some content within the file **book/content-pre-toc.latex** that is not getting transferred to the Epub versions.

**Comment by adamniedzielski** [comment]
Is there a way to move it from the Latex file to the Markdown file so it's shared properly? I think that this would be the best idea if that's possible.

**Comment by adamniedzielski** [comment]
After some research I think that we will not be able to add some Markdown content before the ToC in EPUB. We could add it after the ToC but it will show in the same way as a chapter is shown and will be included in the ToC.

**Comment by adamniedzielski** [comment]
I believe we could leverage the `epub_metadata.md` file for that. You can add to it:

```
rights: "This document is secured with visible and invisible watermarks that connect this copy with the identity of the person who bought it. Legal action will be pursued if this file is uploaded online or made available on BitTorrent.

<br/><br/>The author has repeatedly taken action against infringers in the past.

<br/><br/>All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means, including photocopying, recording, or other electronic or mechanical methods, without the prior written permission of the publisher, except in the case of brief quotations embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For permission requests, contact the published.

<br/><br/>Copyright © 2016 by Jack Kinsella."
```

The drawbacks of this approach are:
1. the text is duplicated
2. we have to use HTML in it

but I cannot come up with any better solution.

**Comment by jackkinsella** [comment]
I found an approach that is working by hand. 

1 unzip the epub
2 add a file "./content-pre-toc.xhtml"
3 update "content.opf" to include this new file within both the manifest and spine tags

```
<manifest>
     <item id="title_page_xhtml" href="title_page.xhtml" media-type="application/xhtml+xml" />
    <item id="content-pre-toc_xhtml" href="content-pre-toc.xhtml" media-type="application/xhtml+xml" />

...

<spine toc="ncx">
    <itemref idref="cover_xhtml" />
    <itemref idref="title_page_xhtml" linear="yes" />
    <itemref idref="content-pre-toc_xhtml" />
...
```

4 rezip with [epzip](https://github.com/takahashim/epzip)

**Comment by jackkinsella** [comment]
@adamniedzielski can you integrate my new script into the Elixir flow?

Right now, it works when I run this:

```
 ./insert-pre-toc-content-to-epub.sh ../book
```

**Comment by adamniedzielski** [comment]
Done here https://github.com/adamniedzielski/admission/commit/cda2bbaec0a7d236df6808e694c8f9b6a96ade1e
