### ISSUE TITLE
Improvements to Table of Contents on Epub/Mobi

### ISSUE THREAD

**Issue by jackkinsella** [adamniedzielski/admission#9]
I noticed what I hope to be the very last issues with the book production before launch:
1. "Entreprenerd" comes up as chapter 1 in the ToC, whereas this isn't even a chapter at all. The first real chapter, SEO, is listed as chapter 2. (I think Pandoc automatically inserts a weird, unnecessary "Entreprenerd" chapter in there)
2. Sections in ToC are numbered even though they shouldn't be (probably just a CSS fix)
3. I want to divide the ToC of the .epub and .mobi into 7 "parts" as I've done with the latest PDF. Unfortunately, this isn't translating over correctly. The relevant bits within the book markdown can be seen in this [commit](https://github.com/jackkinsella/entreprenerd-book/commit/1079017ad35cb9656e193a3965410d961bcad72b).

**Comment by jackkinsella** [comment]
3. I want to divide the ToC of the .epub and .mobi into 7 "parts" as I've done with the latest PDF. Unfortunately, this isn't translating over correctly. The relevant bits within the book markdown can be seen in this [commit](https://github.com/jackkinsella/entreprenerd-book/commit/1079017ad35cb9656e193a3965410d961bcad72b).

**Comment by adamniedzielski** [comment]
1) The offending change which causes the extra "Entreprenerd" heading to be appended and as a consequence the extract chapter in the ToC is "add parts to the PDF book". Somehow `\tocpart{PART A: SEARCH ENGINE OPTIMISIATION}` breaks EPUB generation.

**Comment by adamniedzielski** [comment]
1) I checked the internal Pandoc representation and `\tocpart{PART A: SEARCH ENGINE OPTIMISIATION}` creates a paragraph before the chapter heading. The EPUB converter doesn't like pages which don't start with a heading, so it creates an artificial heading ("Entreprenerd") to fix that.

I searched extensively for a way to divide the book into parts in EPUB, but I didn't find anything. It is not supported by Pandoc and we cannot achieve it with any Pandoc filter.

That's why I believe that the only thing which we can do is remove the separation into parts from the PDF. This will fix the EPUB and MOBI output and we will have consistency across three different formats. I'm disappointed with this solution, because the separation looks really cool. On the other hand, we support multiple formats with a single source, so we have to make a compromise from time to time.

**Comment by adamniedzielski** [comment]
2) It is indeed just a simple CSS fix for EPUB, but it doesn't work for MOBI as per #12

**Comment by jackkinsella** [comment]
1) I think I have a fix for the extra Entreprenerd chapter... going to work on that now.

**Comment by jackkinsella** [comment]
1. ^ repaired on epub by adding an introductory chapter before the first parts directive

**Comment by jackkinsella** [comment]
I'm going to attempt to tackle the third issue (parts in the ToC of epub).

Could you work on the second one (numbering due to .mobi CSS, plus other CSS mobi glitches like the photo in #12)

**Comment by adamniedzielski** [comment]
Sure, I will look what I can do.

**Comment by adamniedzielski** [comment]
I tried to solve these issues for the last two hours, but I didn't make any progress at all :cry:

During the conversion from EPUB to MOBI Calibre rewrites completely the CSS rules, but this process is not documented at all. Some styles are ignored completely and some of them are inlined. It also adds a couple of custom styles.

When I try to remove the numbering, the rules are not passed to the MOBI file - Calibre drops them during the conversion.

The images have hardcoded `width` and `height` properties (in the HTML not in CSS). I don't know how Calibre calculates these dimensions nor how to change them.

I tried to randomly specify some available conversion options described here https://manual.calibre-ebook.com/generated/en/ebook-convert.html but without any luck.

There are no resources in the internet which describe how Calibre handles CSS in MOBI files. I'm stuck and I don't have any more ideas to try.

**Comment by jackkinsella** [comment]
Ok, just to add to the list of "things we tried that didn't work", I attempted conversion with Amazon's kindlegen package, but it complained about the epub not validating according to its special spec.

**Comment by jackkinsella** [comment]
more documentation for my reference: http://manual.calibre-ebook.com/conversion.html

**Comment by jackkinsella** [comment]
OK - re: numbering in the ToC (second point) - screw it, it's not the end of the world.
everything else is done.
